name: Foundry Coverage

on:
  pull_request:
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run coverage
        run: forge coverage --report lcov --ir-minimum

      - name: Filter coverage report
        run: |
          grep -v '/mocks/' ./lcov.info | grep -v '/interfaces/' > ./lcov.filtered.info

      - name: Upload filtered coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./lcov.filtered.info
          token: ${{ secrets.CODECOV_TOKEN }}
